version: 2
updates:
  - package-ecosystem: cargo
    open-pull-requests-limit: 0
    directory: /
    schedule:
      interval: weekly
    groups:
      cargo-patch-and-minor:
        update-types:
          - patch
          - minor
