/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 10ff5876239d1606462087f1437957ca)
interface __BaseEnv_Env {
	RELAY_DOMAIN: "example.com";
	CONTROL_DOMAIN: "relay.example.com";
	RELAY: DurableObjectNamespace /* RelayDurableObject */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./build/worker/shim");
		durableNamespaces: "RelayDurableObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RELAY_DOMAIN" | "CONTROL_DOMAIN">> {}
}
